services:
  database:
    image: postgres:17
    container_name: secure_db
    environment:
      # Allineato con "Database Name" su Easypanel
      POSTGRES_DB: db-2xend
      # Allineato con "User" su Easypanel
      POSTGRES_USER: postgres
      # Allineato con "Password" su Easypanel
      POSTGRES_PASSWORD: 9b9fe57d821d11cc6061
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
